version: '3.7'

services:
    php:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
        container_name: php_scheMgt
        volumes:
            - ./src:/var/www/html
        ports:
            - "9000:9000"

    mysql:
        image: mysql:8.0
        container_name: mysql_scheMgt
        ports:
            - "4306:3306"
        volumes:
            - ./docker/db/data:/var/lib/mysql
            - ./docker/db/my_conf:/etc/mysql/conf.d
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_DATABASE: laravel
            MYSQL_USER: test
            MYSQL_PASSWORD: test

    nginx:
        image: nginx:stable-alpine
        container_name: nginx_scheMgt
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
